# 数据库配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/erp_db
    username: root
    password: root
  # JPA配置  
  jpa:
    hibernate:
      # 自动更新表结构
      ddl-auto: update
    # 显示SQL语句,方便调试
    show-sql: true